var searchData=
[
  ['e_20aggiornamenti_0',['🔄 &lt;b&gt;Manutenzione e Aggiornamenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md101',1,'']]],
  ['e_20apertura_20file_1',['&lt;b&gt;2. Lettura Parametri e Apertura File&lt;/b&gt;',['../index.html#autotoc_md25',1,'']]],
  ['e_20esecuzione_20esempi_2',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['e_20modulo_20grafo_3',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['e_20strutture_20dati_4',['&lt;b&gt;3. Algoritmi e Strutture Dati&lt;/b&gt;',['../index.html#autotoc_md40',1,'']]],
  ['e_20svantaggi_5',['Vantaggi e Svantaggi',['../complessita.html#vantaggi_svantaggi',1,'']]],
  ['e_20tipi_6',['📋 &lt;b&gt;Strutture e Tipi&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md165',1,'']]],
  ['e_20tutorial_7',['📚 &lt;b&gt;Esempi e Tutorial&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md167',1,'']]],
  ['e_20visualizzazione_20grafo_8',['&lt;b&gt;3. Costruzione e Visualizzazione Grafo&lt;/b&gt;',['../index.html#autotoc_md26',1,'']]],
  ['ed_20esecuzione_9',['ed Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione']]],
  ['educativo_10',['🎯 &lt;b&gt;Utilizzo Educativo&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md97',1,'']]],
  ['elem_11',['elem',['../structelem.html',1,'']]],
  ['enqueue_12',['enqueue',['../codap_8cc.html#a0abbd47d8fc3da6acb331a5da3d60d5a',1,'enqueue(codap c, int i, float w):&#160;codap.cc'],['../codap_8h.html#a19dcdc8441d87086bcae44cecc969eb4',1,'enqueue(codap, int, float):&#160;codap.cc']]],
  ['enqueue_20inserimento_20ordinato_13',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;enqueue()&lt;/span&gt; - Inserimento Ordinato&lt;/b&gt;',['../index.html#autotoc_md33',1,'']]],
  ['esecuzione_14',['Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione'],['../compilazione_esempi.html#esecuzione',1,'Esecuzione']]],
  ['esecuzione_20esempi_15',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['eseguire_20con_20un_20file_20grafo_3a_16',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['esempi_17',['Esempi',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md88',1,'💻 <b>Test degli Esempi</b>'],['../compilazione_esempi.html',1,'Compilazione e Esecuzione Esempi']]],
  ['esempi_20di_20utilizzo_18',['Esempi di Utilizzo',['../esempi.html',1,'']]],
  ['esempi_20e_20tutorial_19',['📚 &lt;b&gt;Esempi e Tutorial&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md167',1,'']]],
  ['esempi_20implementati_20',['📊 &lt;b&gt;Esempi Implementati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md96',1,'']]],
  ['esempi_20pratici_21',['✅ &lt;b&gt;Esempi Pratici&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md161',1,'']]],
  ['esempi_5fgrafo_2ecc_22',['esempi_grafo.cc',['../esempi__grafo_8cc.html',1,'']]],
  ['esempio_20base_23',['Esempio Base',['../esempi.html#esempio_base',1,'']]],
  ['esempio_20completo_24',['🎨 Esempio Completo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md137',1,'']]],
  ['esempio_20completo_3a_25',['Esempio Completo:',['../dijkstra_8h.html#autotoc_md4',1,'']]],
  ['esempio_20di_20ricostruzione_20percorso_26',['Esempio di Ricostruzione Percorso',['../md_README__UNIFIED.html#autotoc_md67',1,'']]],
  ['esempio_20di_20ricostruzione_3a_27',['Esempio di Ricostruzione:',['../dijkstra_8h.html#autotoc_md9',1,'']]],
  ['esempio_20pratico_28',['Esempio Pratico',['../md_README__UNIFIED.html#autotoc_md58',1,'']]],
  ['esempio_20pratico_3a_29',['Esempio Pratico:',['../dijkstra_8h.html#autotoc_md2',1,'']]],
  ['esempio_3a_30',['Esempio:',['../dijkstra_8h.html#autotoc_md0',1,'']]],
  ['esempio_5fgrafo_5fnon_5forientato_31',['esempio_grafo_non_orientato',['../esempi__grafo_8cc.html#a73271409e3a52fd55e15c0c6c09adb85',1,'esempi_grafo.cc']]],
  ['esempio_5fgrafo_5forientato_32',['esempio_grafo_orientato',['../esempi__grafo_8cc.html#acf39e5f60302ff209af3ea0937719409',1,'esempi_grafo.cc']]],
  ['esempio_5foperazioni_5favanzate_33',['esempio_operazioni_avanzate',['../esempi__grafo_8cc.html#a04a6394fd5328236ef883a0029ff51d4',1,'esempi_grafo.cc']]],
  ['esempio_5frete_5fstradale_34',['esempio_rete_stradale',['../esempi__grafo_8cc.html#a7df3fa840d7e796c508132baec96daaa',1,'esempi_grafo.cc']]],
  ['esiste_5farco_35',['esiste_arco',['../esempi__grafo_8cc.html#a96ff7393924fd1b00bc9a176d6946f86',1,'esempi_grafo.cc']]],
  ['estrazione_20minimo_36',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;dequeue()&lt;/span&gt; - Estrazione Minimo&lt;/b&gt;',['../index.html#autotoc_md34',1,'']]]
];
