var searchData=
[
  ['dal_20file_0',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['dati_1',['Dati',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md94',1,'🏗️ <b>Strutture Dati</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md155',1,'🏗️ <b>Strutture Dati</b>'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md109',1,'🏗️ Strutture Dati'],['../index.html#autotoc_md40',1,'<b>3. Algoritmi e Strutture Dati</b>'],['../index.html#autotoc_md32',1,'<b>Struttura Dati</b>']]],
  ['dati_20dettagliate_2',['✅ &lt;b&gt;Strutture Dati Dettagliate&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md82',1,'']]],
  ['decrease_5fpriority_3',['Decrease_Priority',['../codap_8cc.html#ae921ab2a6724828519bfff32e13b8e09',1,'Decrease_Priority(codap c, int i, float w):&#160;codap.cc'],['../codap_8h.html#ade7c5c4207e283ca6c8f3959e2f66fbc',1,'Decrease_Priority(codap, int, float):&#160;codap.cc']]],
  ['decrease_5fpriority_20aggiornamento_20priorità_4',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;Decrease_Priority()&lt;/span&gt; - Aggiornamento Priorità&lt;/b&gt;',['../index.html#autotoc_md35',1,'']]],
  ['degli_20esempi_5',['💻 &lt;b&gt;Test degli Esempi&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md88',1,'']]],
  ['dei_20pesi_6',['Somma dei Pesi',['../esempi.html#somma_pesi',1,'']]],
  ['dei_20risultati_7',['🔍 Interpretazione dei Risultati',['../md_README__UNIFIED.html#autotoc_md66',1,'']]],
  ['del_20codice_8',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['del_20grado_9',['Calcolo del Grado',['../esempi.html#calcolo_grado',1,'']]],
  ['del_20grafo_10',['🌐 &lt;span class=&quot;tt&quot;&gt;graph&lt;/span&gt; - Struttura Principale del Grafo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md113',1,'']]],
  ['del_20grafo_20dal_20file_11',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['del_20main_20flusso_20del_20programma_12',['📋 &lt;b&gt;Analisi del &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; - Flusso del Programma&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['del_20percorso_3a_13',['Ricostruzione del Percorso:',['../dijkstra_8h.html#autotoc_md8',1,'']]],
  ['del_20progetto_14',['del Progetto',['../index.html#autotoc_md14',1,'🏗️ Architettura del Progetto'],['../md_README__UNIFIED.html#autotoc_md52',1,'📋 Struttura del Progetto'],['../md_README__UNIFIED.html#autotoc_md50',1,'Panoramica del Progetto'],['../md_README.html#autotoc_md46',1,'Struttura del Progetto']]],
  ['del_20programma_15',['📋 &lt;b&gt;Analisi del &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; - Flusso del Programma&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['del_20rilassamento_3a_16',['Logica del Rilassamento:',['../dijkstra_8h.html#autotoc_md1',1,'']]],
  ['dell_20algoritmo_17',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;relax()&lt;/span&gt; - Cuore dell&apos;Algoritmo&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]],
  ['della_20documentazione_18',['della Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md80',1,'🎯 <b>Caratteristiche della Documentazione</b>'],['../md_README.html#autotoc_md48',1,'Generazione della Documentazione']]],
  ['della_20lista_20di_20adiacenza_19',['🧩 &lt;span class=&quot;tt&quot;&gt;adj_node&lt;/span&gt; - Nodo della Lista di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md110',1,'']]],
  ['della_20memoria_20',['Gestione della Memoria',['../note_implementative.html#gestione_memoria',1,'']]],
  ['dequeue_21',['dequeue',['../codap_8cc.html#a083181fae3220fb0076828bb26b08906',1,'dequeue(codap &amp;c):&#160;codap.cc'],['../codap_8h.html#a650271f7330c7722b5a78a8c454446a0',1,'dequeue(codap &amp;):&#160;codap.cc']]],
  ['dequeue_20estrazione_20minimo_22',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;dequeue()&lt;/span&gt; - Estrazione Minimo&lt;/b&gt;',['../index.html#autotoc_md34',1,'']]],
  ['dest_23',['dest',['../dijkstra_8cc.html#a138b129a81d2c268b8bd4f3d59f2d773',1,'dijkstra.cc']]],
  ['dettagliata_20del_20codice_24',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['dettagliata_3a_20coda_20a_20priorità_20codap_20cc_25',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['dettagliata_3a_20dijkstra_20cc_26',['📋 Analisi Dettagliata: &lt;span class=&quot;tt&quot;&gt;dijkstra.cc&lt;/span&gt;',['../index.html#autotoc_md16',1,'']]],
  ['dettagliate_27',['✅ &lt;b&gt;Strutture Dati Dettagliate&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md82',1,'']]],
  ['di_20accesso_20getter_28',['🔍 Funzioni di Accesso (Getter)',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md122',1,'']]],
  ['di_20adiacenza_29',['di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md112',1,'📊 <span class="tt">adj_list</span> - Tipo Lista di Adiacenza'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md107',1,'📊 Documentazione Modulo Grafo - Liste di Adiacenza'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md110',1,'🧩 <span class="tt">adj_node</span> - Nodo della Lista di Adiacenza']]],
  ['di_20base_30',['Algoritmi di Base',['../esempi.html#esempio_algoritmi',1,'']]],
  ['di_20complessità_31',['di Complessità',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md134',1,'⚡ Analisi di Complessità'],['../complessita.html',1,'Analisi di Complessità']]],
  ['di_20costruzione_32',['🔧 Funzioni di Costruzione',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md115',1,'']]],
  ['di_20dijkstra_33',['di Dijkstra',['../md_README__UNIFIED.html#autotoc_md56',1,'🎯 Focus: Algoritmo di Dijkstra'],['../dijkstra_8h.html#algoritmo',1,'Come Funziona l'Algoritmo di Dijkstra']]],
  ['di_20dijkstra_20analisi_20dettagliata_20del_20codice_34',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['di_20dijkstra_20e_20modulo_20grafo_35',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['di_20dijkstra_20parte_20principale_36',['&lt;b&gt;5. Algoritmo di Dijkstra - Parte Principale&lt;/b&gt;',['../index.html#autotoc_md28',1,'']]],
  ['di_20indice_37',['di Indice',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md140',1,'⚠️ <b>Conversioni di Indice</b>'],['../note_implementative.html#conversioni',1,'Conversioni di Indice']]],
  ['di_20inserimento_38',['di Inserimento',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md118',1,'➕ Funzioni di Inserimento'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md142',1,'🎯 <b>Ordine di Inserimento</b>']]],
  ['di_20output_20mancanti_39',['❌ &lt;b&gt;File di output mancanti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md174',1,'']]],
  ['di_20programmazione_40',['&lt;b&gt;2. Tecniche di Programmazione&lt;/b&gt;',['../index.html#autotoc_md39',1,'']]],
  ['di_20ricostruzione_20percorso_41',['Esempio di Ricostruzione Percorso',['../md_README__UNIFIED.html#autotoc_md67',1,'']]],
  ['di_20ricostruzione_3a_42',['Esempio di Ricostruzione:',['../dijkstra_8h.html#autotoc_md9',1,'']]],
  ['di_20un_20arco_43',['Ricerca di un Arco',['../esempi.html#ricerca_arco',1,'']]],
  ['di_20un_20arco_20specifico_44',['🔍 &lt;b&gt;Ricerca di un Arco Specifico&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md131',1,'']]],
  ['di_20un_20nodo_45',['📊 &lt;b&gt;Calcolo Grado di un Nodo&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md132',1,'']]],
  ['di_20utilizzo_46',['Esempi di Utilizzo',['../esempi.html',1,'']]],
  ['di_20utilizzo_20comuni_47',['🎯 Pattern di Utilizzo Comuni',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md129',1,'']]],
  ['didattici_20avanzati_48',['🎓 &lt;b&gt;Concetti Didattici Avanzati&lt;/b&gt;',['../index.html#autotoc_md37',1,'']]],
  ['dijkstra_49',['Dijkstra',['../md_README__UNIFIED.html#autotoc_md56',1,'🎯 Focus: Algoritmo di Dijkstra'],['../index.html#autotoc_md20',1,'🔧 <b>Funzione <span class="tt">inizialize()</span> - Inizializzazione Dijkstra</b>'],['../index.html#autotoc_md27',1,'<b>4. Allocazione Memoria per Dijkstra</b>'],['../dijkstra_8h.html#algoritmo',1,'Come Funziona l'Algoritmo di Dijkstra'],['../md_README.html',1,'Progetto Dijkstra']]],
  ['dijkstra_50',['dijkstra',['../dijkstra_8h.html#a3c8180d11c01804b34fdd06326a97314',1,'dijkstra.h']]],
  ['dijkstra_20analisi_20dettagliata_20del_20codice_51',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['dijkstra_20cc_52',['📋 Analisi Dettagliata: &lt;span class=&quot;tt&quot;&gt;dijkstra.cc&lt;/span&gt;',['../index.html#autotoc_md16',1,'']]],
  ['dijkstra_20e_20modulo_20grafo_53',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['dijkstra_20parte_20principale_54',['&lt;b&gt;5. Algoritmo di Dijkstra - Parte Principale&lt;/b&gt;',['../index.html#autotoc_md28',1,'']]],
  ['dijkstra_20principale_55',['Modulo Dijkstra (Principale)',['../md_README__UNIFIED.html#autotoc_md53',1,'']]],
  ['dijkstra_2ecc_56',['dijkstra.cc',['../dijkstra_8cc.html',1,'']]],
  ['dijkstra_2eh_57',['dijkstra.h',['../dijkstra_8h.html',1,'']]],
  ['dim_58',['dim',['../structgraph.html#a9def34128f4a4d912cb9a595a7f492c1',1,'graph']]],
  ['docenti_59',['👨‍🏫 &lt;b&gt;Per Docenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md99',1,'']]],
  ['documentate_60',['✅ &lt;b&gt;Funzioni Documentate&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md83',1,'']]],
  ['documentati_61',['📚 &lt;b&gt;Contenuti Documentati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md93',1,'']]],
  ['documentazione_62',['Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md158',1,'🎨 Caratteristiche Documentazione'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md80',1,'🎯 <b>Caratteristiche della Documentazione</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md149',1,'📁 File Documentazione'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md154',1,'📖 Contenuto Documentazione'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md102',1,'📝 <b>Modifica Documentazione</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md163',1,'🔍 Navigazione Documentazione'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md85',1,'🚀 <b>Come Utilizzare la Documentazione</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md150',1,'🚀 Generazione Documentazione'],['../md_README.html#autotoc_md48',1,'Generazione della Documentazione']]],
  ['documentazione_20api_63',['📚 Documentazione API',['../md_README__UNIFIED.html#autotoc_md69',1,'']]],
  ['documentazione_20completa_20per_20studio_20universitario_64',['Documentazione Completa per Studio Universitario',['../index.html',1,'']]],
  ['documentazione_20creata_20con_20successo_65',['🎉 Documentazione Creata con Successo!',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md76',1,'']]],
  ['documentazione_20doxygen_20completa_20modulo_20grafo_66',['📚 DOCUMENTAZIONE DOXYGEN COMPLETA - MODULO GRAFO',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html',1,'']]],
  ['documentazione_20doxygen_20modulo_20grafo_67',['📚 Documentazione Doxygen - Modulo Grafo',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html',1,'']]],
  ['documentazione_20modulo_20grafo_20liste_20di_20adiacenza_68',['📊 Documentazione Modulo Grafo - Liste di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md107',1,'']]],
  ['documentazione_20principale_69',['📖 &lt;b&gt;Documentazione Principale&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md78',1,'']]],
  ['documentazione_5fcompleta_2emd_70',['DOCUMENTAZIONE_COMPLETA.md',['../DOCUMENTAZIONE__COMPLETA_8md.html',1,'']]],
  ['documentazione_5fstudio_2emd_71',['DOCUMENTAZIONE_STUDIO.md',['../DOCUMENTAZIONE__STUDIO_8md.html',1,'']]],
  ['doxygen_72',['🔧 &lt;b&gt;Configurazione Doxygen&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md91',1,'']]],
  ['doxygen_20completa_20modulo_20grafo_73',['📚 DOCUMENTAZIONE DOXYGEN COMPLETA - MODULO GRAFO',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html',1,'']]],
  ['doxygen_20modulo_20grafo_74',['📚 Documentazione Doxygen - Modulo Grafo',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html',1,'']]],
  ['doxygen_20non_20trovato_75',['❌ &lt;b&gt;Doxygen non trovato&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md173',1,'']]],
  ['durante_20generazione_76',['❌ &lt;b&gt;Warning durante generazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md175',1,'']]]
];
