var searchData=
[
  ['pagina_20principale_0',['🏠 &lt;b&gt;Pagina Principale&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md164',1,'']]],
  ['panoramica_1',['Panoramica',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md148',1,'🎯 Panoramica'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md108',1,'📋 Panoramica']]],
  ['panoramica_20del_20progetto_2',['Panoramica del Progetto',['../md_README__UNIFIED.html#autotoc_md50',1,'']]],
  ['parametri_3',['&lt;b&gt;1. Controllo Parametri&lt;/b&gt;',['../index.html#autotoc_md24',1,'']]],
  ['parametri_20e_20apertura_20file_4',['&lt;b&gt;2. Lettura Parametri e Apertura File&lt;/b&gt;',['../index.html#autotoc_md25',1,'']]],
  ['parent_5',['parent',['../dijkstra_8cc.html#a8e99857563320b5d943128e5816b1d70',1,'dijkstra.cc']]],
  ['parte_20principale_6',['&lt;b&gt;5. Algoritmo di Dijkstra - Parte Principale&lt;/b&gt;',['../index.html#autotoc_md28',1,'']]],
  ['passo_20passo_3a_7',['Algoritmo Passo-Passo:',['../dijkstra_8h.html#autotoc_md3',1,'']]],
  ['passo_3a_8',['Algoritmo Passo-Passo:',['../dijkstra_8h.html#autotoc_md3',1,'']]],
  ['pattern_20di_20utilizzo_20comuni_9',['🎯 Pattern di Utilizzo Comuni',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md129',1,'']]],
  ['per_20aggiunta_20archi_10',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;add()&lt;/span&gt; - Wrapper per Aggiunta Archi&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['per_20dijkstra_11',['&lt;b&gt;4. Allocazione Memoria per Dijkstra&lt;/b&gt;',['../index.html#autotoc_md27',1,'']]],
  ['per_20docenti_12',['👨‍🏫 &lt;b&gt;Per Docenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md99',1,'']]],
  ['per_20lo_20studio_20universitario_13',['Guida per lo Studio Universitario',['../dijkstra_8h.html#studio',1,'']]],
  ['per_20studenti_14',['👨‍🎓 &lt;b&gt;Per Studenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md98',1,'']]],
  ['per_20studio_20universitario_15',['Documentazione Completa per Studio Universitario',['../index.html',1,'']]],
  ['per_20sviluppatori_16',['💼 &lt;b&gt;Per Sviluppatori&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md100',1,'']]],
  ['percorso_17',['Esempio di Ricostruzione Percorso',['../md_README__UNIFIED.html#autotoc_md67',1,'']]],
  ['percorso_3a_18',['Ricostruzione del Percorso:',['../dijkstra_8h.html#autotoc_md8',1,'']]],
  ['performance_19',['⚡ &lt;b&gt;Performance&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md92',1,'']]],
  ['personalizzazione_20',['Personalizzazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md103',1,'⚙️ <b>Personalizzazione</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md168',1,'⚙️ Personalizzazione'],['../compilazione_esempi.html#personalizzazione',1,'Personalizzazione']]],
  ['pesi_21',['Somma dei Pesi',['../esempi.html#somma_pesi',1,'']]],
  ['possibili_20studio_22',['🔍 &lt;b&gt;Miglioramenti Possibili (Studio)&lt;/b&gt;',['../index.html#autotoc_md43',1,'']]],
  ['pratici_23',['✅ &lt;b&gt;Esempi Pratici&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md161',1,'']]],
  ['pratico_24',['Esempio Pratico',['../md_README__UNIFIED.html#autotoc_md58',1,'']]],
  ['pratico_3a_25',['Esempio Pratico:',['../dijkstra_8h.html#autotoc_md2',1,'']]],
  ['prerequisiti_26',['📋 Prerequisiti',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md151',1,'']]],
  ['principale_27',['Principale',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md164',1,'🏠 <b>Pagina Principale</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md78',1,'📖 <b>Documentazione Principale</b>'],['../index.html#autotoc_md28',1,'<b>5. Algoritmo di Dijkstra - Parte Principale</b>'],['../md_README__UNIFIED.html#autotoc_md53',1,'Modulo Dijkstra (Principale)']]],
  ['principale_20del_20grafo_28',['🌐 &lt;span class=&quot;tt&quot;&gt;graph&lt;/span&gt; - Struttura Principale del Grafo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md113',1,'']]],
  ['principali_29',['Principali',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md95',1,'🔧 <b>Funzioni Principali</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md156',1,'🔧 <b>Funzioni Principali</b>']]],
  ['priorità_30',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;Decrease_Priority()&lt;/span&gt; - Aggiornamento Priorità&lt;/b&gt;',['../index.html#autotoc_md35',1,'']]],
  ['priorità_20codap_20cc_31',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['problemi_32',['Problemi',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md104',1,'🐛 <b>Risoluzione Problemi</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md172',1,'🐛 Risoluzione Problemi']]],
  ['professionale_33',['Professionale',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md81',1,'✅ <b>Completezza Professionale</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md160',1,'✅ <b>Stile Professionale</b>']]],
  ['progetto_34',['Progetto',['../index.html#autotoc_md14',1,'🏗️ Architettura del Progetto'],['../md_README__UNIFIED.html#autotoc_md52',1,'📋 Struttura del Progetto'],['../md_README__UNIFIED.html#autotoc_md50',1,'Panoramica del Progetto'],['../md_README.html#autotoc_md46',1,'Struttura del Progetto']]],
  ['progetto_20dijkstra_35',['Progetto Dijkstra',['../md_README.html',1,'']]],
  ['progetto_3a_36',['Compilare il progetto:',['../md_README__UNIFIED.html#autotoc_md61',1,'']]],
  ['progetto_3a_20algoritmo_20di_20dijkstra_20e_20modulo_20grafo_37',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['programma_38',['📋 &lt;b&gt;Analisi del &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; - Flusso del Programma&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['programmazione_39',['&lt;b&gt;2. Tecniche di Programmazione&lt;/b&gt;',['../index.html#autotoc_md39',1,'']]],
  ['proprietà_20importante_3a_40',['Proprietà Importante:',['../dijkstra_8h.html#autotoc_md5',1,'']]],
  ['pubblicazione_20web_41',['🌐 &lt;b&gt;Pubblicazione Web&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md179',1,'']]],
  ['pun_42',['pun',['../structelem.html#a5676f3bc339c6078388c93534e0ddbb2',1,'elem']]]
];
