var searchData=
[
  ['a_20priorità_20codap_20cc_0',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['accesso_20getter_1',['🔍 Funzioni di Accesso (Getter)',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md122',1,'']]],
  ['add_2',['add',['../dijkstra_8cc.html#a50209542568b8a154fd31fb0014f7272',1,'dijkstra.cc']]],
  ['add_20wrapper_20per_20aggiunta_20archi_3',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;add()&lt;/span&gt; - Wrapper per Aggiunta Archi&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['add_5farc_4',['add_arc',['../grafo_8cc.html#a0d455da463c949e9613e0c485b594c2c',1,'add_arc(graph &amp;G, int u, int v, float w):&#160;grafo.cc'],['../grafo_8h.html#ac755cfbd1059bf061b902d375daa1f54',1,'add_arc(graph &amp;, int, int, float):&#160;grafo.cc'],['../grafo__documented_8h.html#a0d455da463c949e9613e0c485b594c2c',1,'add_arc(graph &amp;G, int u, int v, float w):&#160;grafo.cc']]],
  ['add_5farc_20graph_20g_20int_20u_20int_20v_20float_20w_5',['🎯 &lt;span class=&quot;tt&quot;&gt;add_arc(graph&amp;amp; G, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'']]],
  ['add_5fedge_6',['add_edge',['../grafo_8cc.html#abc598efa270218e51b6d4b74e4908173',1,'add_edge(graph &amp;g, int u, int v, float w):&#160;grafo.cc'],['../grafo_8h.html#a846ce8021e6febcb7a39654fe6f60694',1,'add_edge(graph &amp;g, int, int, float):&#160;grafo.cc'],['../grafo__documented_8h.html#abc598efa270218e51b6d4b74e4908173',1,'add_edge(graph &amp;g, int u, int v, float w):&#160;grafo.cc']]],
  ['add_5fedge_20graph_20g_20int_20u_20int_20v_20float_20w_7',['🔄 &lt;span class=&quot;tt&quot;&gt;add_edge(graph&amp;amp; g, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'']]],
  ['adiacenza_8',['Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md112',1,'📊 <span class="tt">adj_list</span> - Tipo Lista di Adiacenza'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md107',1,'📊 Documentazione Modulo Grafo - Liste di Adiacenza'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md110',1,'🧩 <span class="tt">adj_node</span> - Nodo della Lista di Adiacenza']]],
  ['adj_5flist_9',['adj_list',['../grafo_8h.html#a7304f6ecd4c575848d0b173d254317d6',1,'adj_list:&#160;grafo.h'],['../grafo__documented_8h.html#a7304f6ecd4c575848d0b173d254317d6',1,'adj_list:&#160;grafo_documented.h']]],
  ['adj_5flist_20l_10',['➡️ &lt;span class=&quot;tt&quot;&gt;get_nextadj(adj_list l)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md127',1,'']]],
  ['adj_5flist_20tipo_20lista_20di_20adiacenza_11',['📊 &lt;span class=&quot;tt&quot;&gt;adj_list&lt;/span&gt; - Tipo Lista di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md112',1,'']]],
  ['adj_5fnode_12',['adj_node',['../structadj__node.html',1,'']]],
  ['adj_5fnode_20l_13',['adj_node l',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md126',1,'⚖️ <span class="tt">get_adjweight(adj_node* l)</span>'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md125',1,'🔢 <span class="tt">get_adjnode(adj_node* l)</span>']]],
  ['adj_5fnode_20nodo_20della_20lista_20di_20adiacenza_14',['🧩 &lt;span class=&quot;tt&quot;&gt;adj_node&lt;/span&gt; - Nodo della Lista di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md110',1,'']]],
  ['aggiornamenti_15',['🔄 &lt;b&gt;Manutenzione e Aggiornamenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md101',1,'']]],
  ['aggiornamento_20priorità_16',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;Decrease_Priority()&lt;/span&gt; - Aggiornamento Priorità&lt;/b&gt;',['../index.html#autotoc_md35',1,'']]],
  ['aggiunta_20archi_17',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;add()&lt;/span&gt; - Wrapper per Aggiunta Archi&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['aggiunta_20contenuti_18',['📝 &lt;b&gt;Aggiunta Contenuti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md170',1,'']]],
  ['algoritmi_20di_20base_19',['Algoritmi di Base',['../esempi.html#esempio_algoritmi',1,'']]],
  ['algoritmi_20e_20strutture_20dati_20',['&lt;b&gt;3. Algoritmi e Strutture Dati&lt;/b&gt;',['../index.html#autotoc_md40',1,'']]],
  ['algoritmo_21',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;relax()&lt;/span&gt; - Cuore dell&apos;Algoritmo&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]],
  ['algoritmo_20di_20dijkstra_22',['Algoritmo di Dijkstra',['../md_README__UNIFIED.html#autotoc_md56',1,'🎯 Focus: Algoritmo di Dijkstra'],['../dijkstra_8h.html#algoritmo',1,'Come Funziona l'Algoritmo di Dijkstra']]],
  ['algoritmo_20di_20dijkstra_20analisi_20dettagliata_20del_20codice_23',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['algoritmo_20di_20dijkstra_20e_20modulo_20grafo_24',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['algoritmo_20di_20dijkstra_20parte_20principale_25',['&lt;b&gt;5. Algoritmo di Dijkstra - Parte Principale&lt;/b&gt;',['../index.html#autotoc_md28',1,'']]],
  ['algoritmo_20passo_20passo_3a_26',['Algoritmo Passo-Passo:',['../dijkstra_8h.html#autotoc_md3',1,'']]],
  ['allocazione_20memoria_20per_20dijkstra_27',['&lt;b&gt;4. Allocazione Memoria per Dijkstra&lt;/b&gt;',['../index.html#autotoc_md27',1,'']]],
  ['analisi_20del_20main_20flusso_20del_20programma_28',['📋 &lt;b&gt;Analisi del &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; - Flusso del Programma&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['analisi_20dettagliata_20del_20codice_29',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['analisi_20dettagliata_3a_20coda_20a_20priorità_20codap_20cc_30',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['analisi_20dettagliata_3a_20dijkstra_20cc_31',['📋 Analisi Dettagliata: &lt;span class=&quot;tt&quot;&gt;dijkstra.cc&lt;/span&gt;',['../index.html#autotoc_md16',1,'']]],
  ['analisi_20di_20complessità_32',['Analisi di Complessità',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md134',1,'⚡ Analisi di Complessità'],['../complessita.html',1,'Analisi di Complessità']]],
  ['apertura_20file_33',['&lt;b&gt;2. Lettura Parametri e Apertura File&lt;/b&gt;',['../index.html#autotoc_md25',1,'']]],
  ['api_34',['📚 Documentazione API',['../md_README__UNIFIED.html#autotoc_md69',1,'']]],
  ['archi_35',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;add()&lt;/span&gt; - Wrapper per Aggiunta Archi&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['architettura_20del_20progetto_36',['🏗️ Architettura del Progetto',['../index.html#autotoc_md14',1,'']]],
  ['arco_37',['Ricerca di un Arco',['../esempi.html#ricerca_arco',1,'']]],
  ['arco_20specifico_38',['🔍 &lt;b&gt;Ricerca di un Arco Specifico&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md131',1,'']]],
  ['aspetto_39',['🎨 &lt;b&gt;Modifica Aspetto&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md169',1,'']]],
  ['atteso_40',['Output Atteso',['../compilazione_esempi.html#output',1,'']]],
  ['avanzata_41',['🔧 &lt;b&gt;Configurazione Avanzata&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md171',1,'']]],
  ['avanzati_42',['🎓 &lt;b&gt;Concetti Didattici Avanzati&lt;/b&gt;',['../index.html#autotoc_md37',1,'']]],
  ['avanzato_43',['🚀 Utilizzo Avanzato',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md177',1,'']]]
];
