var searchData=
[
  ['i_20nodi_0',['🔄 &lt;b&gt;Iterazione su Tutti i Nodi&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md130',1,'']]],
  ['il_20progetto_3a_1',['Compilare il progetto:',['../md_README__UNIFIED.html#autotoc_md61',1,'']]],
  ['implementati_2',['📊 &lt;b&gt;Esempi Implementati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md96',1,'']]],
  ['implementative_3',['Implementative',['../md_README__UNIFIED.html#autotoc_md73',1,'📖 Note Implementative'],['../note_implementative.html',1,'Note Implementative']]],
  ['importante_3a_4',['Proprietà Importante:',['../dijkstra_8h.html#autotoc_md5',1,'']]],
  ['importanti_5',['🔒 Note Importanti',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md139',1,'']]],
  ['indice_6',['Indice',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md140',1,'⚠️ <b>Conversioni di Indice</b>'],['../note_implementative.html#conversioni',1,'Conversioni di Indice']]],
  ['inf_7',['inf',['../structelem.html#a437b0acb286ff7fe4e298d4d2b851c7b',1,'elem']]],
  ['inizialize_8',['inizialize',['../dijkstra_8cc.html#af7743a128b0ad4c16fc76257b6eab34d',1,'dijkstra.cc']]],
  ['inizialize_20inizializzazione_20dijkstra_9',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;inizialize()&lt;/span&gt; - Inizializzazione Dijkstra&lt;/b&gt;',['../index.html#autotoc_md20',1,'']]],
  ['inizializza_5fdijkstra_10',['inizializza_dijkstra',['../dijkstra_8h.html#ac43cb1a224d4631ff2c336f60f142a52',1,'dijkstra.h']]],
  ['inizializzazione_20dijkstra_11',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;inizialize()&lt;/span&gt; - Inizializzazione Dijkstra&lt;/b&gt;',['../index.html#autotoc_md20',1,'']]],
  ['inserimento_12',['Inserimento',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md118',1,'➕ Funzioni di Inserimento'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md142',1,'🎯 <b>Ordine di Inserimento</b>']]],
  ['inserimento_20ordinato_13',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;enqueue()&lt;/span&gt; - Inserimento Ordinato&lt;/b&gt;',['../index.html#autotoc_md33',1,'']]],
  ['int_20n_14',['🏗️ &lt;span class=&quot;tt&quot;&gt;new_graph(int n)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md116',1,'']]],
  ['int_20u_15',['📋 &lt;span class=&quot;tt&quot;&gt;get_adjlist(graph g, int u)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md124',1,'']]],
  ['int_20u_20int_20v_20float_20w_16',['int u int v float w',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'🎯 <span class="tt">add_arc(graph&amp; G, int u, int v, float w)</span>'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'🔄 <span class="tt">add_edge(graph&amp; g, int u, int v, float w)</span>']]],
  ['int_20v_20float_20w_17',['int v float w',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'🎯 <span class="tt">add_arc(graph&amp; G, int u, int v, float w)</span>'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'🔄 <span class="tt">add_edge(graph&amp; g, int u, int v, float w)</span>']]],
  ['integrazione_20ci_20cd_18',['📖 &lt;b&gt;Integrazione CI/CD&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md178',1,'']]],
  ['interpretazione_20dei_20risultati_19',['🔍 Interpretazione dei Risultati',['../md_README__UNIFIED.html#autotoc_md66',1,'']]],
  ['interpretazione_3a_20',['Interpretazione:',['../dijkstra_8h.html#autotoc_md7',1,'']]],
  ['introduzione_21',['📚 Introduzione',['../index.html#autotoc_md12',1,'']]],
  ['isempty_22',['isEmpty',['../codap_8cc.html#a2420dce951b719ee0a06df5bcbd83673',1,'isEmpty(codap c):&#160;codap.cc'],['../codap_8h.html#acca9b3ae10221160ecc30a2d8eaeb0b0',1,'isEmpty(codap):&#160;codap.cc']]],
  ['iterazione_20su_20tutti_20i_20nodi_23',['🔄 &lt;b&gt;Iterazione su Tutti i Nodi&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md130',1,'']]]
];
