var searchData=
[
  ['calcola_5fgrado_5fuscita_0',['calcola_grado_uscita',['../esempi__grafo_8cc.html#a16022b473f2fcde2052515457eada1f5',1,'esempi_grafo.cc']]],
  ['calcolo_20del_20grado_1',['Calcolo del Grado',['../esempi.html#calcolo_grado',1,'']]],
  ['calcolo_20grado_20di_20un_20nodo_2',['📊 &lt;b&gt;Calcolo Grado di un Nodo&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md132',1,'']]],
  ['campi_3a_3',['Campi:',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md111',1,'📝 Campi:'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md114',1,'📝 Campi:']]],
  ['caratteristiche_20della_20documentazione_4',['🎯 &lt;b&gt;Caratteristiche della Documentazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md80',1,'']]],
  ['caratteristiche_20documentazione_5',['🎨 Caratteristiche Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md158',1,'']]],
  ['caratteristiche_20tecniche_6',['🎨 &lt;b&gt;Caratteristiche Tecniche&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md89',1,'']]],
  ['cartella_20grafo_7',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['cc_8',['cc',['../index.html#autotoc_md31',1,'📋 <b>Analisi Dettagliata: Coda a Priorità (<span class="tt">codap.cc</span>)</b>'],['../index.html#autotoc_md16',1,'📋 Analisi Dettagliata: <span class="tt">dijkstra.cc</span>']]],
  ['cd_9',['📖 &lt;b&gt;Integrazione CI/CD&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md178',1,'']]],
  ['ci_20cd_10',['📖 &lt;b&gt;Integrazione CI/CD&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md178',1,'']]],
  ['coda_20a_20priorità_20codap_20cc_11',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['codap_12',['codap',['../codap_8h.html#a48e727c6d4f1af018b0ce079b934a446',1,'codap.h']]],
  ['codap_20cc_13',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['codap_2ecc_14',['codap.cc',['../codap_8cc.html',1,'']]],
  ['codap_2eh_15',['codap.h',['../codap_8h.html',1,'']]],
  ['codice_16',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['come_20funziona_17',['Come Funziona',['../md_README__UNIFIED.html#autotoc_md57',1,'']]],
  ['come_20funziona_20l_20algoritmo_20di_20dijkstra_18',['Come Funziona l&apos;Algoritmo di Dijkstra',['../dijkstra_8h.html#algoritmo',1,'']]],
  ['come_20utilizzare_20la_20documentazione_19',['🚀 &lt;b&gt;Come Utilizzare la Documentazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md85',1,'']]],
  ['compilare_20il_20progetto_3a_20',['Compilare il progetto:',['../md_README__UNIFIED.html#autotoc_md61',1,'']]],
  ['compilazione_21',['Compilazione',['../compilazione_esempi.html#compilazione',1,'']]],
  ['compilazione_20e_20esecuzione_20esempi_22',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['compilazione_20ed_20esecuzione_23',['Compilazione ed Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione']]],
  ['complessità_24',['Complessità',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md134',1,'⚡ Analisi di Complessità'],['../complessita.html',1,'Analisi di Complessità']]],
  ['complessità_20computazionale_25',['Complessità Computazionale',['../md_README__UNIFIED.html#autotoc_md64',1,'📊 Complessità Computazionale'],['../index.html#autotoc_md41',1,'<b>4. Complessità Computazionale</b>']]],
  ['complessità_20spaziale_26',['Complessità Spaziale',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md135',1,'📊 <b>Complessità Spaziale</b>'],['../complessita.html#complessita_spaziale',1,'Complessità Spaziale']]],
  ['complessità_20temporale_27',['Complessità Temporale',['../complessita.html#complessita_temporale',1,'']]],
  ['completa_20modulo_20grafo_28',['📚 DOCUMENTAZIONE DOXYGEN COMPLETA - MODULO GRAFO',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html',1,'']]],
  ['completa_20per_20studio_20universitario_29',['Documentazione Completa per Studio Universitario',['../index.html',1,'']]],
  ['completezza_30',['✅ &lt;b&gt;Completezza&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md159',1,'']]],
  ['completezza_20professionale_31',['✅ &lt;b&gt;Completezza Professionale&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md81',1,'']]],
  ['completo_32',['🎨 Esempio Completo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md137',1,'']]],
  ['completo_3a_33',['Esempio Completo:',['../dijkstra_8h.html#autotoc_md4',1,'']]],
  ['computazionale_34',['Computazionale',['../md_README__UNIFIED.html#autotoc_md64',1,'📊 Complessità Computazionale'],['../index.html#autotoc_md41',1,'<b>4. Complessità Computazionale</b>']]],
  ['comuni_35',['🎯 Pattern di Utilizzo Comuni',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md129',1,'']]],
  ['con_20successo_36',['🎉 Documentazione Creata con Successo!',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md76',1,'']]],
  ['con_20un_20file_20grafo_3a_37',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['concetti_20didattici_20avanzati_38',['🎓 &lt;b&gt;Concetti Didattici Avanzati&lt;/b&gt;',['../index.html#autotoc_md37',1,'']]],
  ['configurazione_20avanzata_39',['🔧 &lt;b&gt;Configurazione Avanzata&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md171',1,'']]],
  ['configurazione_20doxygen_40',['🔧 &lt;b&gt;Configurazione Doxygen&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md91',1,'']]],
  ['contenuti_41',['📝 &lt;b&gt;Aggiunta Contenuti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md170',1,'']]],
  ['contenuti_20documentati_42',['📚 &lt;b&gt;Contenuti Documentati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md93',1,'']]],
  ['contenuto_20documentazione_43',['📖 Contenuto Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md154',1,'']]],
  ['controllo_20parametri_44',['&lt;b&gt;1. Controllo Parametri&lt;/b&gt;',['../index.html#autotoc_md24',1,'']]],
  ['conversioni_20di_20indice_45',['Conversioni di Indice',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md140',1,'⚠️ <b>Conversioni di Indice</b>'],['../note_implementative.html#conversioni',1,'Conversioni di Indice']]],
  ['correlati_46',['📚 File Correlati',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md145',1,'']]],
  ['costruzione_47',['🔧 Funzioni di Costruzione',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md115',1,'']]],
  ['costruzione_20del_20grafo_20dal_20file_48',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['costruzione_20e_20visualizzazione_20grafo_49',['&lt;b&gt;3. Costruzione e Visualizzazione Grafo&lt;/b&gt;',['../index.html#autotoc_md26',1,'']]],
  ['creata_20con_20successo_50',['🎉 Documentazione Creata con Successo!',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md76',1,'']]],
  ['creati_20nella_20cartella_20grafo_51',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['cuore_20dell_20algoritmo_52',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;relax()&lt;/span&gt; - Cuore dell&apos;Algoritmo&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]]
];
