var searchData=
[
  ['file_0',['File',['../index.html#autotoc_md19',1,'🔧 <b>Funzione <span class="tt">g_build()</span> - Costruzione del Grafo dal File</b>'],['../index.html#autotoc_md25',1,'<b>2. Lettura Parametri e Apertura File</b>']]],
  ['file_20correlati_1',['📚 File Correlati',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md145',1,'']]],
  ['file_20creati_20nella_20cartella_20grafo_2',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['file_20di_20output_20mancanti_3',['❌ &lt;b&gt;File di output mancanti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md174',1,'']]],
  ['file_20documentazione_4',['📁 File Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md149',1,'']]],
  ['file_20grafo_3a_5',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['finale_6',['🏆 &lt;b&gt;Risultato Finale&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md105',1,'']]],
  ['flessibilità_7',['🔄 &lt;b&gt;Flessibilità&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md143',1,'']]],
  ['float_20w_8',['float w',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'🎯 <span class="tt">add_arc(graph&amp; G, int u, int v, float w)</span>'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'🔄 <span class="tt">add_edge(graph&amp; g, int u, int v, float w)</span>']]],
  ['flusso_20del_20programma_9',['📋 &lt;b&gt;Analisi del &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; - Flusso del Programma&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['focus_3a_20algoritmo_20di_20dijkstra_10',['🎯 Focus: Algoritmo di Dijkstra',['../md_README__UNIFIED.html#autotoc_md56',1,'']]],
  ['formato_20output_3a_11',['Formato Output:',['../dijkstra_8h.html#autotoc_md6',1,'']]],
  ['funziona_12',['Come Funziona',['../md_README__UNIFIED.html#autotoc_md57',1,'']]],
  ['funziona_20l_20algoritmo_20di_20dijkstra_13',['Come Funziona l&apos;Algoritmo di Dijkstra',['../dijkstra_8h.html#algoritmo',1,'']]],
  ['funzione_20add_20wrapper_20per_20aggiunta_20archi_14',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;add()&lt;/span&gt; - Wrapper per Aggiunta Archi&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['funzione_20decrease_5fpriority_20aggiornamento_20priorità_15',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;Decrease_Priority()&lt;/span&gt; - Aggiornamento Priorità&lt;/b&gt;',['../index.html#autotoc_md35',1,'']]],
  ['funzione_20dequeue_20estrazione_20minimo_16',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;dequeue()&lt;/span&gt; - Estrazione Minimo&lt;/b&gt;',['../index.html#autotoc_md34',1,'']]],
  ['funzione_20enqueue_20inserimento_20ordinato_17',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;enqueue()&lt;/span&gt; - Inserimento Ordinato&lt;/b&gt;',['../index.html#autotoc_md33',1,'']]],
  ['funzione_20g_5fbuild_20costruzione_20del_20grafo_20dal_20file_18',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['funzione_20inizialize_20inizializzazione_20dijkstra_19',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;inizialize()&lt;/span&gt; - Inizializzazione Dijkstra&lt;/b&gt;',['../index.html#autotoc_md20',1,'']]],
  ['funzione_20relax_20cuore_20dell_20algoritmo_20',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;relax()&lt;/span&gt; - Cuore dell&apos;Algoritmo&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]],
  ['funzioni_21',['🔧 &lt;b&gt;Riferimento Funzioni&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md166',1,'']]],
  ['funzioni_20di_20accesso_20getter_22',['🔍 Funzioni di Accesso (Getter)',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md122',1,'']]],
  ['funzioni_20di_20costruzione_23',['🔧 Funzioni di Costruzione',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md115',1,'']]],
  ['funzioni_20di_20inserimento_24',['➕ Funzioni di Inserimento',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md118',1,'']]],
  ['funzioni_20documentate_25',['✅ &lt;b&gt;Funzioni Documentate&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md83',1,'']]],
  ['funzioni_20principali_26',['Funzioni Principali',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md95',1,'🔧 <b>Funzioni Principali</b>'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md156',1,'🔧 <b>Funzioni Principali</b>']]]
];
