var searchData=
[
  ['calcolo_20del_20grado_0',['Calcolo del Grado',['../esempi.html#calcolo_grado',1,'']]],
  ['calcolo_20grado_20di_20un_20nodo_1',['📊 &lt;b&gt;Calcolo Grado di un Nodo&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md132',1,'']]],
  ['campi_3a_2',['Campi:',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md111',1,'📝 Campi:'],['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md114',1,'📝 Campi:']]],
  ['caratteristiche_20della_20documentazione_3',['🎯 &lt;b&gt;Caratteristiche della Documentazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md80',1,'']]],
  ['caratteristiche_20documentazione_4',['🎨 Caratteristiche Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md158',1,'']]],
  ['caratteristiche_20tecniche_5',['🎨 &lt;b&gt;Caratteristiche Tecniche&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md89',1,'']]],
  ['cartella_20grafo_6',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['cc_7',['cc',['../index.html#autotoc_md31',1,'📋 <b>Analisi Dettagliata: Coda a Priorità (<span class="tt">codap.cc</span>)</b>'],['../index.html#autotoc_md16',1,'📋 Analisi Dettagliata: <span class="tt">dijkstra.cc</span>']]],
  ['cd_8',['📖 &lt;b&gt;Integrazione CI/CD&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md178',1,'']]],
  ['ci_20cd_9',['📖 &lt;b&gt;Integrazione CI/CD&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md178',1,'']]],
  ['coda_20a_20priorità_20codap_20cc_10',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['codap_20cc_11',['📋 &lt;b&gt;Analisi Dettagliata: Coda a Priorità (&lt;span class=&quot;tt&quot;&gt;codap.cc&lt;/span&gt;)&lt;/b&gt;',['../index.html#autotoc_md31',1,'']]],
  ['codice_12',['Algoritmo di Dijkstra - Analisi Dettagliata del Codice',['../index.html#autotoc_md11',1,'']]],
  ['come_20funziona_13',['Come Funziona',['../md_README__UNIFIED.html#autotoc_md57',1,'']]],
  ['come_20funziona_20l_20algoritmo_20di_20dijkstra_14',['Come Funziona l&apos;Algoritmo di Dijkstra',['../dijkstra_8h.html#algoritmo',1,'']]],
  ['come_20utilizzare_20la_20documentazione_15',['🚀 &lt;b&gt;Come Utilizzare la Documentazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md85',1,'']]],
  ['compilare_20il_20progetto_3a_16',['Compilare il progetto:',['../md_README__UNIFIED.html#autotoc_md61',1,'']]],
  ['compilazione_17',['Compilazione',['../compilazione_esempi.html#compilazione',1,'']]],
  ['compilazione_20e_20esecuzione_20esempi_18',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['compilazione_20ed_20esecuzione_19',['Compilazione ed Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione']]],
  ['complessità_20',['Complessità',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md134',1,'⚡ Analisi di Complessità'],['../complessita.html',1,'Analisi di Complessità']]],
  ['complessità_20computazionale_21',['Complessità Computazionale',['../md_README__UNIFIED.html#autotoc_md64',1,'📊 Complessità Computazionale'],['../index.html#autotoc_md41',1,'<b>4. Complessità Computazionale</b>']]],
  ['complessità_20spaziale_22',['Complessità Spaziale',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md135',1,'📊 <b>Complessità Spaziale</b>'],['../complessita.html#complessita_spaziale',1,'Complessità Spaziale']]],
  ['complessità_20temporale_23',['Complessità Temporale',['../complessita.html#complessita_temporale',1,'']]],
  ['completa_20modulo_20grafo_24',['📚 DOCUMENTAZIONE DOXYGEN COMPLETA - MODULO GRAFO',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html',1,'']]],
  ['completa_20per_20studio_20universitario_25',['Documentazione Completa per Studio Universitario',['../index.html',1,'']]],
  ['completezza_26',['✅ &lt;b&gt;Completezza&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md159',1,'']]],
  ['completezza_20professionale_27',['✅ &lt;b&gt;Completezza Professionale&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md81',1,'']]],
  ['completo_28',['🎨 Esempio Completo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md137',1,'']]],
  ['completo_3a_29',['Esempio Completo:',['../dijkstra_8h.html#autotoc_md4',1,'']]],
  ['computazionale_30',['Computazionale',['../md_README__UNIFIED.html#autotoc_md64',1,'📊 Complessità Computazionale'],['../index.html#autotoc_md41',1,'<b>4. Complessità Computazionale</b>']]],
  ['comuni_31',['🎯 Pattern di Utilizzo Comuni',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md129',1,'']]],
  ['con_20successo_32',['🎉 Documentazione Creata con Successo!',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md76',1,'']]],
  ['con_20un_20file_20grafo_3a_33',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['concetti_20didattici_20avanzati_34',['🎓 &lt;b&gt;Concetti Didattici Avanzati&lt;/b&gt;',['../index.html#autotoc_md37',1,'']]],
  ['configurazione_20avanzata_35',['🔧 &lt;b&gt;Configurazione Avanzata&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md171',1,'']]],
  ['configurazione_20doxygen_36',['🔧 &lt;b&gt;Configurazione Doxygen&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md91',1,'']]],
  ['contenuti_37',['📝 &lt;b&gt;Aggiunta Contenuti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md170',1,'']]],
  ['contenuti_20documentati_38',['📚 &lt;b&gt;Contenuti Documentati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md93',1,'']]],
  ['contenuto_20documentazione_39',['📖 Contenuto Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md154',1,'']]],
  ['controllo_20parametri_40',['&lt;b&gt;1. Controllo Parametri&lt;/b&gt;',['../index.html#autotoc_md24',1,'']]],
  ['conversioni_20di_20indice_41',['Conversioni di Indice',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md140',1,'⚠️ <b>Conversioni di Indice</b>'],['../note_implementative.html#conversioni',1,'Conversioni di Indice']]],
  ['correlati_42',['📚 File Correlati',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md145',1,'']]],
  ['costruzione_43',['🔧 Funzioni di Costruzione',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md115',1,'']]],
  ['costruzione_20del_20grafo_20dal_20file_44',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['costruzione_20e_20visualizzazione_20grafo_45',['&lt;b&gt;3. Costruzione e Visualizzazione Grafo&lt;/b&gt;',['../index.html#autotoc_md26',1,'']]],
  ['creata_20con_20successo_46',['🎉 Documentazione Creata con Successo!',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md76',1,'']]],
  ['creati_20nella_20cartella_20grafo_47',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['cuore_20dell_20algoritmo_48',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;relax()&lt;/span&gt; - Cuore dell&apos;Algoritmo&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]]
];
