var searchData=
[
  ['e_20aggiornamenti_0',['🔄 &lt;b&gt;Manutenzione e Aggiornamenti&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md101',1,'']]],
  ['e_20apertura_20file_1',['&lt;b&gt;2. Lettura Parametri e Apertura File&lt;/b&gt;',['../index.html#autotoc_md25',1,'']]],
  ['e_20esecuzione_20esempi_2',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['e_20modulo_20grafo_3',['Progetto: Algoritmo di Dijkstra e Modulo Grafo',['../md_README__UNIFIED.html',1,'']]],
  ['e_20strutture_20dati_4',['&lt;b&gt;3. Algoritmi e Strutture Dati&lt;/b&gt;',['../index.html#autotoc_md40',1,'']]],
  ['e_20svantaggi_5',['Vantaggi e Svantaggi',['../complessita.html#vantaggi_svantaggi',1,'']]],
  ['e_20tipi_6',['📋 &lt;b&gt;Strutture e Tipi&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md165',1,'']]],
  ['e_20tutorial_7',['📚 &lt;b&gt;Esempi e Tutorial&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md167',1,'']]],
  ['e_20visualizzazione_20grafo_8',['&lt;b&gt;3. Costruzione e Visualizzazione Grafo&lt;/b&gt;',['../index.html#autotoc_md26',1,'']]],
  ['ed_20esecuzione_9',['ed Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione']]],
  ['educativo_10',['🎯 &lt;b&gt;Utilizzo Educativo&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md97',1,'']]],
  ['enqueue_20inserimento_20ordinato_11',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;enqueue()&lt;/span&gt; - Inserimento Ordinato&lt;/b&gt;',['../index.html#autotoc_md33',1,'']]],
  ['esecuzione_12',['Esecuzione',['../md_README__UNIFIED.html#autotoc_md60',1,'🔧 Compilazione ed Esecuzione'],['../md_README.html#autotoc_md47',1,'Compilazione ed Esecuzione'],['../compilazione_esempi.html#esecuzione',1,'Esecuzione']]],
  ['esecuzione_20esempi_13',['Compilazione e Esecuzione Esempi',['../compilazione_esempi.html',1,'']]],
  ['eseguire_20con_20un_20file_20grafo_3a_14',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['esempi_15',['Esempi',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md88',1,'💻 <b>Test degli Esempi</b>'],['../compilazione_esempi.html',1,'Compilazione e Esecuzione Esempi']]],
  ['esempi_20di_20utilizzo_16',['Esempi di Utilizzo',['../esempi.html',1,'']]],
  ['esempi_20e_20tutorial_17',['📚 &lt;b&gt;Esempi e Tutorial&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md167',1,'']]],
  ['esempi_20implementati_18',['📊 &lt;b&gt;Esempi Implementati&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md96',1,'']]],
  ['esempi_20pratici_19',['✅ &lt;b&gt;Esempi Pratici&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md161',1,'']]],
  ['esempio_20base_20',['Esempio Base',['../esempi.html#esempio_base',1,'']]],
  ['esempio_20completo_21',['🎨 Esempio Completo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md137',1,'']]],
  ['esempio_20completo_3a_22',['Esempio Completo:',['../dijkstra_8h.html#autotoc_md4',1,'']]],
  ['esempio_20di_20ricostruzione_20percorso_23',['Esempio di Ricostruzione Percorso',['../md_README__UNIFIED.html#autotoc_md67',1,'']]],
  ['esempio_20di_20ricostruzione_3a_24',['Esempio di Ricostruzione:',['../dijkstra_8h.html#autotoc_md9',1,'']]],
  ['esempio_20pratico_25',['Esempio Pratico',['../md_README__UNIFIED.html#autotoc_md58',1,'']]],
  ['esempio_20pratico_3a_26',['Esempio Pratico:',['../dijkstra_8h.html#autotoc_md2',1,'']]],
  ['esempio_3a_27',['Esempio:',['../dijkstra_8h.html#autotoc_md0',1,'']]],
  ['estrazione_20minimo_28',['&lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;dequeue()&lt;/span&gt; - Estrazione Minimo&lt;/b&gt;',['../index.html#autotoc_md34',1,'']]]
];
