var searchData=
[
  ['g_0',['📏 &lt;span class=&quot;tt&quot;&gt;get_dim(graph g)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md123',1,'']]],
  ['g_20int_20u_1',['📋 &lt;span class=&quot;tt&quot;&gt;get_adjlist(graph g, int u)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md124',1,'']]],
  ['g_20int_20u_20int_20v_20float_20w_2',['🎯 &lt;span class=&quot;tt&quot;&gt;add_arc(graph&amp;amp; G, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'']]],
  ['g_20int_20u_20int_20v_20float_20w_3',['🔄 &lt;span class=&quot;tt&quot;&gt;add_edge(graph&amp;amp; g, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'']]],
  ['g_5fbuild_20costruzione_20del_20grafo_20dal_20file_4',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['generate_5',['📊 &lt;b&gt;Statistiche Generate&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md90',1,'']]],
  ['generato_6',['🌐 &lt;b&gt;Output HTML Generato&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md79',1,'']]],
  ['generazione_7',['❌ &lt;b&gt;Warning durante generazione&lt;/b&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md175',1,'']]],
  ['generazione_20della_20documentazione_8',['Generazione della Documentazione',['../md_README.html#autotoc_md48',1,'']]],
  ['generazione_20documentazione_9',['🚀 Generazione Documentazione',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md150',1,'']]],
  ['generazione_20manuale_10',['🔧 Generazione Manuale',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md153',1,'']]],
  ['generazione_20rapida_11',['⚡ Generazione Rapida',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html#autotoc_md152',1,'']]],
  ['gestione_20della_20memoria_12',['Gestione della Memoria',['../note_implementative.html#gestione_memoria',1,'']]],
  ['gestione_20memoria_13',['Gestione Memoria',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md141',1,'🧠 <b>Gestione Memoria</b>'],['../index.html#autotoc_md38',1,'<b>1. Gestione Memoria</b>']]],
  ['get_5fadjlist_20graph_20g_20int_20u_14',['📋 &lt;span class=&quot;tt&quot;&gt;get_adjlist(graph g, int u)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md124',1,'']]],
  ['get_5fadjnode_20adj_5fnode_20l_15',['🔢 &lt;span class=&quot;tt&quot;&gt;get_adjnode(adj_node* l)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md125',1,'']]],
  ['get_5fadjweight_20adj_5fnode_20l_16',['⚖️ &lt;span class=&quot;tt&quot;&gt;get_adjweight(adj_node* l)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md126',1,'']]],
  ['get_5fdim_20graph_20g_17',['📏 &lt;span class=&quot;tt&quot;&gt;get_dim(graph g)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md123',1,'']]],
  ['get_5fnextadj_20adj_5flist_20l_18',['➡️ &lt;span class=&quot;tt&quot;&gt;get_nextadj(adj_list l)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md127',1,'']]],
  ['getter_19',['🔍 Funzioni di Accesso (Getter)',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md122',1,'']]],
  ['globali_20',['🔧 &lt;b&gt;Variabili Globali&lt;/b&gt;',['../index.html#autotoc_md17',1,'']]],
  ['grado_21',['Calcolo del Grado',['../esempi.html#calcolo_grado',1,'']]],
  ['grado_20di_20un_20nodo_22',['📊 &lt;b&gt;Calcolo Grado di un Nodo&lt;/b&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md132',1,'']]],
  ['grafo_23',['📚 DOCUMENTAZIONE DOXYGEN COMPLETA - MODULO GRAFO',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html',1,'']]],
  ['grafo_24',['Grafo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md113',1,'🌐 <span class="tt">graph</span> - Struttura Principale del Grafo'],['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2README__DOCS.html',1,'📚 Documentazione Doxygen - Modulo Grafo'],['../index.html#autotoc_md26',1,'<b>3. Costruzione e Visualizzazione Grafo</b>'],['../md_README__UNIFIED.html',1,'Progetto: Algoritmo di Dijkstra e Modulo Grafo']]],
  ['grafo_25',['📁 File Creati nella Cartella &lt;span class=&quot;tt&quot;&gt;grafo/&lt;/span&gt;',['../md__2Users_2alessandrobilotti_2Desktop_2uni_2Primo_01Anno_2UniMoRe_2Prog2_2Lez20_2grafo_2DOCUMENTAZIONE__COMPLETA.html#autotoc_md77',1,'']]],
  ['grafo_20dal_20file_26',['🔧 &lt;b&gt;Funzione &lt;span class=&quot;tt&quot;&gt;g_build()&lt;/span&gt; - Costruzione del Grafo dal File&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['grafo_20liste_20di_20adiacenza_27',['📊 Documentazione Modulo Grafo - Liste di Adiacenza',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md107',1,'']]],
  ['grafo_20supporto_28',['Modulo Grafo (Supporto)',['../md_README__UNIFIED.html#autotoc_md54',1,'']]],
  ['grafo_3a_29',['Eseguire con un file grafo:',['../md_README__UNIFIED.html#autotoc_md62',1,'']]],
  ['graph_20g_30',['📏 &lt;span class=&quot;tt&quot;&gt;get_dim(graph g)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md123',1,'']]],
  ['graph_20g_20int_20u_31',['📋 &lt;span class=&quot;tt&quot;&gt;get_adjlist(graph g, int u)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md124',1,'']]],
  ['graph_20g_20int_20u_20int_20v_20float_20w_32',['🎯 &lt;span class=&quot;tt&quot;&gt;add_arc(graph&amp;amp; G, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md119',1,'']]],
  ['graph_20g_20int_20u_20int_20v_20float_20w_33',['🔄 &lt;span class=&quot;tt&quot;&gt;add_edge(graph&amp;amp; g, int u, int v, float w)&lt;/span&gt;',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md120',1,'']]],
  ['graph_20struttura_20principale_20del_20grafo_34',['🌐 &lt;span class=&quot;tt&quot;&gt;graph&lt;/span&gt; - Struttura Principale del Grafo',['..//Users/alessandrobilotti/Desktop/uni/Primo Anno/UniMoRe/Prog2/Lez20/grafo/README.md#autotoc_md113',1,'']]],
  ['guida_20per_20lo_20studio_20universitario_35',['Guida per lo Studio Universitario',['../dijkstra_8h.html#studio',1,'']]]
];
